### ISSUE TITLE
Google Maps API key now required when inputting address in the post file generator

### ISSUE THREAD

**Issue by HarryBagman** [ArthurG/Kijiji-Repost-Headless#119]
In july 2018 this came into effect. Here is the error produced:

Maps API error: Keyless access to Google Maps Platform is deprecated. Please use an API key with all your API calls to avoid service interruption. For further details please refer to http://g.co/dev/maps-no-account

Any solution to this besides paying google?

**Comment by jackm** [comment]
I only briefly looked at their new API policy with them now requiring keys. It says that you can get an API key for free, and it will work for free up to $200 worth of API calls per month (no idea if that's a reasonable amount or not).

However I don't quite know how to approach this. I don't think it makes sense to hard code in somebody's API key so that everybody ends up using it.

Google must have some solution for developers who share their code and need to make Maps API calls without also having to share an API key that's supposed to be private. I haven't found out what that solution is yet though. Maybe moving to an alternative such as OpenStreetMap is a better option?

**Comment by HarryBagman** [comment]
I think the $200 of API calls per month is good enough for a high posting user. Perhaps the code can be modified so the user is prompted to input their specific google API key via the text interface during the post file generator script. If this option is not selected then the script could default to using OSM.
The google API website isn't responding to me currently so I will have to try and enable billing another time. 

Personally I would prefer if OSM's API was exclusively used instead of google's API. I have limited python coding ability so I cannot really be of much assistance.

**Comment by HarryBagman** [comment]
Try editing an existing item.yml file and inputting the new post data including the location information and it should work. This should bypass the API calls all together.
