### ISSUE TITLE
Unable to parse passwords with dollar signs

### ISSUE THREAD

**Issue by discoinfiltrator** [ArthurG/Kijiji-Repost-Headless#125]
If you run a command like:

```
python3 kijiji_repost_headless -u email@gmail.com -p wiRf4f2F6Zip0DvZZ$ubls0IfuxKD5xQVl0P5VCUT show
```

The password is parsed as:

```
wiRf4f2F6Zip0DvZZ
```

**Comment by jackm** [comment]
You will likely have to use single quotes around the password string so that the shell parses it correctly. 

Dollar sign characters are used for variable dereferencing in most shells, which is why it's cutting off the latter half of the password in the example. The shell variable `ubls0IfuxKD5xQVl0P5VCUT` is unlikely to be defined, and thus dereferences to an empty string, therefore the text `wiRf4f2F6Zip0DvZZ$ubls0IfuxKD5xQVl0P5VCUT` gets interpreted by the shell as just `wiRf4f2F6Zip0DvZZ`.

This 'problem' is due to how the shell parses input, not with this python module.

**Comment by discoinfiltrator** [comment]
Sounds good!
