### ISSUE TITLE
Why does the code try to upload images up to 3 times?

### ISSUE THREAD

**Issue by terminator14** [ArthurG/Kijiji-Repost-Headless#160]
In kijiji_api.py, you'll find this code:

```
def upload_image(self, token, image_files=[]):
    ...
    for img_file in image_files:
        for i in range(0, 3):
        ...
            try:
                ...
                print("Image upload success on try #{}".format(i+1))
```

Is there a reason it tries multiple times to upload each image?
It appears that it is doing exactly the same thing every time. Is there a scenario where it fails the first time, but works the second time, even though we didn't change anything?

Is this maybe some workaround for some known issue with kijiji's image upload service, where it doesn't always work or something?

I went digging in commit messages, but couldn't find any explanation for this.

**Comment by jackm** [comment]
I believe that this was a bit of a hack to get image uploading to work more consistently. It tries up to three times (arbitrarily chosen) to upload the image via HTTP POST, and if it succeeds it will break out of the loop, otherwise it will try again up to three times total before it gives up.

This commit was made back in July 2017 so it's quite possible that the multi-try approach isn't necessary any more. I haven't noticed it fail uploading an image after the first try ever for at least a year now.

**Comment by terminator14** [comment]
I was just curious if this was trying to fix a known issue with uploading images, where it would sometimes fail, or if this was a "just in case" thing. Sounds like it's the latter.

I've added code to my projects "just in case" in the past, which made the code more complex, and didn't actually fix anything, since there was no known problem I was addressing.

To be fair, this isn't a whole lot of extra code.

I'm working on a similar project for my mom for personal use, and was borrowing some of the code from this project. I came across that, and wasn't sure if I should take a similar 3-tries approach, or just try once.

Thanks
