### ISSUE TITLE
BannedException

### ISSUE THREAD

**Issue by kirillsavine** [ArthurG/Kijiji-Repost-Headless#49]
I am looking at the following exception in your kijiji_api.py file:
```
class BannedException(KijijiApiException):
    def __str__(self):
        return "Could not post ad, this user is banned.\n"+super().__str__()
```
I constantly run into this exception. 
I realize that this happens if session finds the following string in the response after posting:
`There was an issue posting your ad, please contact Customer Service.`
Even when I try to post manually using a web browser, I get the same issue.
Looks like I am banned. 
Do you have any workaround for this? Is this temporary or permanent for my username? Any advise on how to avoid this in the future?

**Comment by vesper8** [comment]
any idea what you might have done to get on Kijiji's bad side?

**Comment by kirillsavine** [comment]
i just posted 3 ads one after another under 3 different location codes. in
attempt to post 4rth one i get this exception

**Comment by vesper8** [comment]
you could make a dummy account with a throwaway email and see if you can reproduce.. multiple ads in different locations.. but put dummy titles/descriptions.. so as not to jeopardize your real ads then try to isolate what is causing the issue

it could be that you raised a flag because you posted them too quickly.. or have been reposting after deleting too quickly.. or they just don't like someone posting in multiple locations.. could be lots of things I guess but you can probably get around it by adding more delays and maybe using different accounts for different locations

**Comment by justinwrightit** [comment]
I noticed certain images will get your user banned very quickly after posting. If your ad is selling something that may be against Kijiji terms, or someone in the past used your same images for such ads, you'll end up banned very quickly. 

Just create a new gmail account such as "kirillsavine@gmail.com", when registering for kijiji use the email "kirillsavine+ad1@gmail.com" or whatever else you want to add after the +. You then can create filters in your gmail inbox to organize, & easily swap out + extensions when/if users get banned.
