### ISSUE TITLE
How to extract page number from JSON?

### ISSUE THREAD

**Issue by vipertemp** [ArthurG/Kijiji-Repost-Headless#70]
How can I extract the ad page numbers from JSON?
Preferably all of them in a single list object.

I'm not super familiar with JSON stuff at all.

Thanks

**Comment by vipertemp** [comment]
I tried to list all the JSON object properties using this code

`for entry in ads_json['ads'].values():
  for x in entry:
    print(x)`

and got the following results:

id
views
replies
title
thumbnailUrl
priceType
priceAmount
superState
canRepost
isDelayed
isPending
isOnHold
isActive
canConfirm
isExpired
isPriceDropAvailable
endDate
postingDate
deleteReasons
repostReasons
featureOptions

**Comment by jackm** [comment]
I recall that with the old json page (`/j-get-my-ads.json`), the json object did include which page an ad was on. However it would appear that this new json object does not have such information.

**Comment by vipertemp** [comment]
So how does the website display it in my browser? Is there any way this value can be obtained? I need it to make my program even function :(

**Comment by jackm** [comment]
Found it!

After looking at the network requests (hint: use the browser developer console) after loading `https://www.kijiji.ca/m-my-ads.html`, I saw a network request to `https://www.kijiji.ca/my/ranks?ids=<ad_id1>&ids=<ad_id2>&...`.

Turns out the `/my/ranks` page returns the page of the ad ID given to it in json format! So all you actually have to do is make an HTTP request to `/my/ranks` and fill in the `ids` parameter with an ad ID that you want to look up the page "rank" (ie. page number) for. You can give it as many `ids` parameters as you'd like and it will return the rank for each one.

eg.
`GET https://www.kijiji.ca/my/ranks?ids=1234567890&ids=1234567891&ids=1234567892`
will respond with
```
{
  "ranks": {
    "1234567890": 1,
    "1234567891": 2,
    "1234567892": 7
  },
  "_links": {
    "self": {
      "href": "/my/ranks?ids=1234567890&ids=1234567891&ids=1234567892"
    }
  }
}
```
Where the "ranks" of each ad is 1, 2 and 7, respectively.

**Comment by vipertemp** [comment]
Nice! I encounter a 401 error when I call it from inside my program. It works fine when I paste the URL into my browser. I am calling the function to list the page numbers AFTER I already log in, how is this even possible?

**Comment by jackm** [comment]
Are you certain that you are sending the HTTP GET request using the same requests session that you logged in with? You have to send the login cookies when you make the request otherwise the Kijiji server won't know who you are.

I did a small test by adding the following code to the `get_all_ads` function, right before the final return statement.

```
param_str = ""
for id in ad_ids:
        param_str += "ids={}&".format(id)
resp = self.session.get('https://www.kijiji.ca/my/ranks?{}'.format(param_str))
resp.raise_for_status()
ranks_json = json.loads(resp.text)
ad_ranks = ranks_json['ranks']
```

This gets each active ad rank in the dict `ad_ranks`.

**Comment by vipertemp** [comment]
Ok, I'm able to get the numbers now, thank you again -- but I am having difficulty with the login part. What exactly is the cookie and how do I send it, or pass it around?

**Comment by jackm** [comment]
As long as you use the same [session object](http://docs.python-requests.org/en/master/api/#request-sessions) that you used when logging in when making future HTTP requests, it will handle cookies persistence for you. You don't need to use HTTPBasicAuth at all if you're already logged in.

**Comment by jackm** [comment]
Just created a new PR #76 for supporting retrieval of the current ad page number

**Comment by jackm** [comment]
@ArthurG this can be closed now that the PR has been merged.
