### ISSUE TITLE
what is the rationale behind the new version?

### ISSUE THREAD

**Issue by Peppershaker** [ArthurG/Kijiji-Repost-Headless#77]
Hey guys, what's the added benefit of using the new version of the program? Just wondering.

Thanks,

**Comment by jackm** [comment]
What version are you talking about?

**Comment by Peppershaker** [comment]
the commit that changed  move towards YAML. just wondering if i should upgrade or use the .inf file versions. i think read somewhere in the commit notes that the autoconversion to yaml might be not 100% correct.

**Comment by jackm** [comment]
In my opinion YAML is a much better and manageable markup language to use for the ad files. It's a widely used language and it is meant for the very purpose we're using it for; certainly better than making up our own markup syntax. With YAML you get a bunch of extra features for free which are part of the core language.

I realize that for many this doesn't matter because most people won't be manually editing their ad files after they've generated them, but using YAML is still a better direction to go.

I included a python script that can convert inf ad files to the new yml format. The reason why I say that auto conversion might not be 100% correct is because I did not test it for every possible edge case however for the vast majority of inf ad files it should work fine. Some types of ads require additional special fields (eg. car sale ads, rental ads, etc) which you may have to add in manually. This was the same case for the inf ad files.

**Comment by Peppershaker** [comment]
okay great. thanks a lot for the input!

Could you please give me some pointers on how to make the double new lines characters (new row and blank row) work? Right now if I have \n\n it will only show up as a single \n in the ad post. Unless I manually click on the "edit ad" button.

I was thinking of writing a selenium script that will do this, but its sounds heavy and not a good way to implement. any points would help!

**Comment by jackm** [comment]
That's a conversation that should be discussed in issue #52 

My workaround is to add three line breaks where ever I want a blank line to appear in the ad when rendered on the actual ad page.

**Comment by Peppershaker** [comment]
I'll consider that a fix!! Thank you so much !

**Comment by crowbarsolutions** [comment]
Wondering why the ability to have login information in a file was removed?

**Comment by jackm** [comment]
@crowbarsolutions That feature hasn't been removed, it has always been there. Just like before you can always include a `username` and `password` field in an ad post file if you wish.

The "build_ad" subcommand still has this too; it will ask for a Kijiji username and password when generating an ad post file.
