### ISSUE TITLE
500 Server Error: for url: https://www.kijiji.ca/my/ranks

### ISSUE THREAD

**Issue by salvi951** [ArthurG/Kijiji-Repost-Headless#80]
I cannot post any ad because this exception shows up :

requests.exceptions.HTTPError: 500 Server Error: for url: https://www.kijiji.ca/my/ranks

I'm a little new to programming so I apologize in advance if this is very simple. Thanks for your help!

**Comment by jackm** [comment]
Do you have any existing ads right now? There may be an edge case that was overlooked and untested.

**Comment by salvi951** [comment]
No I don't. I tried using two different accounts but both of them show the same error.

**Comment by resiproxy** [comment]
Just validated with two of my accounts.

Account #1 with no Ad had this issue
Account #2 with active had did not have this issue.

Manually added ad on Account #1, ran script again and it now works.

Looks like if it does not have an active ad it will not post?

**Comment by jackm** [comment]
I just made a fix in [list-ad-rank-fix](https://github.com/jackm/Kijiji-Repost-Headless/tree/list-ad-rank-fix) branch. I believe the problem is that even when there are no active ads, it will still try to find the ad rankings (ie. page numbers) but this fails because there are no ads to check in the first place.

Clone this branch and try posting a new ad using an account that has no active ads to confirm that it fixes the bug.

`git clone -b list-ad-rank-fix https://github.com/jackm/Kijiji-Repost-Headless.git`

**Comment by resiproxy** [comment]
I will say this is resolved now :)

**Comment by jackm** [comment]
I just confirmed it as well using a new Kijiji account with no prior active ads. I'll submit a PR for the fix.
